name: hvp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - absl-py=2.0.0
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - async-timeout=4.0.2
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.6.3
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cachetools=5.3.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cryptography=41.0.3
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.2.140
  - cuda-runtime=12.1.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-auth=2.23.3
  - google-auth-oauthlib=1.0.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.7.2.10
  - libcurand=10.3.3.141
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.5
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.26.0
  - numpy-base=1.26.0
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.11
  - pillow=10.0.1
  - pip=23.3
  - protobuf=3.20.3
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tensorboard=2.14.1
  - tensorboard-data-server=0.7.0
  - tk=8.6.12
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - werkzeug=3.0.0
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - antlr4-python3-runtime==4.9.3
      - cmake==3.27.7
      - einops==0.6.1
      - fsspec==2023.9.2
      - lit==17.0.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.2.140
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - packaging==23.2
      - torch==2.1.0
      - torch-summary==1.4.5
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - tqdm==4.66.1
      - triton==2.1.0
