arch: vit_small
img_size: 224
patch_size: 16
out_dim: 65536
norm_last_layer: false
momentum_teacher: 0.996
use_bn_in_head: false
teacher_temp: 0.07
warmup_teacher_temp: 0.04
warmup_teacher_temp_epochs: 30
fp16: false
batch_size: 1024
clip_grad: 0.0
drop_path_rate: 0.1
epochs: 800
warmup_epochs: 10
freeze_last_layer: 1
lr: 0.0005
min_lr: 1.0e-05
optimizer: adamw
weight_decay: 0.04
weight_decay_end: 0.4
global_crops_scale:
- 0.25
- 1.0
global_crops_size: 224
local_crops_number: 10
local_crops_scale:
- 0.05
- 0.25
local_crops_size: 96
limit_comparisons: 64
num_global_crops_loader: 4
num_local_crops_loader: 16
select_fn: cross
dataset: ImageNet
data_path: /p/data1/mmlaion/imagenet-1K-webdataset
dist_backend: nccl
dist_url: env://
grad_accum_steps: 1
log_freq: 50
num_workers: 10
print_freq: 100
saveckp_freq: 0
seed: 1234
output_dir: .
use_adv_metric: false
adv_metric_freq: 10
scale_factor_select: 1.0
hvp_step: 1
