arch: vit_small
img_size: 224
patch_size: 16
avgpool: false
batch_size: 1024
epochs: 100
lr: 0.001
momentum: 0.9
n_last_blocks: 4
optimizer: sgd
weight_decay: 0.0
crop_size: 224
resize_size: 256
dataset: imagenet
data_path: /p/fastdata/mmlaion/imagenet-1K-webdataset
dist_backend: nccl
dist_url: env://
ckp_key: teacher
pretrained: checkpoint.pth
log_freq: 100
num_workers: 10
output_dir: .
val_freq: 1
finetune: false
seed: 0